/*
? [2023] Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms, you may use Microchip 
    software and any derivatives exclusively with Microchip products. 
    You are responsible for complying with 3rd party license terms  
    applicable to your use of 3rd party software (including open source  
    software) that may accompany Microchip software. SOFTWARE IS ?AS IS.? 
    NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS 
    SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT,  
    MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT 
    WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY 
    KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF 
    MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE 
    FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP?S 
    TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL NOT 
    EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR 
    THIS SOFTWARE.
*/

#include <stdio.h>
#include "mcc_generated_files/system/system.h"
#include "mcc_generated_files/system/pins.h"
#include "mcc_generated_files/can/can_tp.h"
#include "mcc_generated_files/can/can_tp_config.h"
#include "mcc_generated_files/timer/tmr1.h"
#include <libpic30.h>

#if defined(CAN_TP_PAUSE_ON_FIRST_FRAME) && CAN_TP_PAUSE_ON_FIRST_FRAME == true
//This line can be removed manually once a call to CAN_TP_Resume() has been made allowing the passing of packets to continue.
#error "If pause on first frame is enabled the device will not send packets after First Frame until CAN_TP_RxResume() has been called."
#endif

//1 second delay depending on the clock frequency
#define LONG_DELAY 4000000
uint8_t rxBuffer[512];

//Allows the device to show a Single Frame being sent
uint8_t txBuffer[3] = {3, 0, 0};

int currentState = 3;
int tickStates[5] = {10, 100, 300, 500, 1000};

bool startedSendingLoop = false;

int tickCount = 1000;
int ticksMax = 1000;

//Sets the state that will lengthen or shorten the time between led toggles.
void Set_Ticks(int newTicksCount)
{    
    ticksMax = tickStates[newTicksCount];
    tickCount = tickStates[newTicksCount];
}

void BUTTON_Pressed(void)
{
    if(!startedSendingLoop)
    {
        startedSendingLoop = true;
        //kicks off the message sending loop
        CAN_TP_MessageSend(txBuffer, sizeof(txBuffer));
    }
}

void Update_Message(void)
{
    if(currentState == 4)
    {
        txBuffer[0] = currentState;
        currentState = 0;
    }
    else
    {
        txBuffer[0] = currentState;
        currentState++;
    }
    
}

void LED_Tick(void)
{
    if(tickCount > 0 && startedSendingLoop)
    {
        tickCount--;
    }
}

/**
 * To allow the use of one timer for multiple tick counters.
 * 
 * calls the CAN_TP_TICK and handles the LED blink timing.
 */
void Custom_Ticks(void)
{
    CAN_TP_Tick();
    LED_Tick();
    if(tickCount == 0)
    {
        LED_Toggle();
        tickCount = ticksMax;
    }
    
}

/*
    Main application
*/
int main(void)
{
    SYSTEM_Initialize();
    
    CAN_TP_Initialize();
    
    //Timer1.TimeoutCallbackRegister(&CAN_TP_Tick);
    
    //The above TimeoutCallbackRegister is generated by the CAN-TP module.
    //This module requires a 1ms timer too but this demo shows how you can utilize a single timer 
    Timer1.TimeoutCallbackRegister(&Custom_Ticks);
    
    BUTTON_SetInterruptHandler(&BUTTON_Pressed);
    
    while(1)
    {         
        CAN_TP_Tasks();
        
        if(CAN_TP_IsMessageReady())
        {
            startedSendingLoop = true;
            CAN_TP_MessageGet(rxBuffer);
            Set_Ticks(rxBuffer[0]);
            Update_Message();
            __delay32(LONG_DELAY);
            CAN_TP_MessageSend(txBuffer, sizeof(txBuffer));
        }
    }    
}